spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.100:3306/sell?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true

server:
  port: 8080
  servlet:
    context-path: /sell
